

function SETUP_TROPA(tipo){

	TIPO_NAVE=tipo
	
	// >>>>>>>>>
	// Variáveis facilitadoras para equilibrar atributos:
					
			//ALCANCE DE REALOCAMENTO DAS TROPAS (DISTANCIA EM PIXELS):
				var ALCANCE_R_px_PADRAO_NIVEL_0 = 500;
				var ALCANCE_R_px_PADRAO_NIVEL_1 = 530;
				var ALCANCE_R_px_PADRAO_NIVEL_2 = 560;
				var ALCANCE_R_px_PADRAO_NIVEL_3 = 600;
	
					var ALCANCE_R_px_BONUS_TERRA = 1.1;

			//ALCANCE DE REALOCAMENTO DAS TROPAS (ANGULO):
				var ALCANCE_R_an_PADRAO_NIVEL_0 = 90;
				var ALCANCE_R_an_PADRAO_NIVEL_1 = 100;
				var ALCANCE_R_an_PADRAO_NIVEL_2 = 120;
				var ALCANCE_R_an_PADRAO_NIVEL_3 = 150;
	
					var ALCANCE_R_an_BONUS_TERRA = 1;
					
			//VELOCIDADE DE REPOSIÇÃO DAS TROPAS (COUNTDOWN):
				var VELOCIDADE_R_PADRAO_NIVEL_0 = 1000;
				var VELOCIDADE_R_PADRAO_NIVEL_1 = 900;
				var VELOCIDADE_R_PADRAO_NIVEL_2 = 800;
				var VELOCIDADE_R_PADRAO_NIVEL_3 = 650;
				
			//Número de naves menores(FILHOS):
				var N_NAVES_PADRAO_NIVEL_0 = 3;
				var N_NAVES_PADRAO_NIVEL_1 = 3;
				var N_NAVES_PADRAO_NIVEL_2 = 3;
				var N_NAVES_PADRAO_NIVEL_3 = 3;

			//VIDA TROPA:
				var VIDA_PADRAO_NIVEL_0 = 50;
				var VIDA_PADRAO_NIVEL_1 = 80;
				var VIDA_PADRAO_NIVEL_2 = 90;
				var VIDA_PADRAO_NIVEL_3 = 100;
	
					var VIDA_BONUS_TERRA = 1.2;

			//DANO TROPA:
				var DANO_PADRAO_NIVEL_0 = 5;
				var DANO_PADRAO_NIVEL_1 = 8;
				var DANO_PADRAO_NIVEL_2 = 9;
				var DANO_PADRAO_NIVEL_3 = 10;
				
			//TEMPO DE RECARGA (COUNTDOWN) DE ATAQUE DA NAVE MENOR:
				var RECARGA_ATAQUE_PADRAO_NIVEL_0 = 80;
				var RECARGA_ATAQUE_PADRAO_NIVEL_1 = 30;
				var RECARGA_ATAQUE_PADRAO_NIVEL_2 = 20;
				var RECARGA_ATAQUE_PADRAO_NIVEL_3 = 10;
	
				
			//MODIFICADORES ELEMENTAR DE VANTAGEM E DESVANTAGEM EM DANO CAUSADO:
				var VANTAGEM_ELEMENTAR_PADRAO	  = 1.2;
				var DESVANTAGEM_ELEMENTAR_PADRAO  = 0.5;
			
	// Variáveis facilitadoras para equilibrar atributos
	// <<<<<<<<<

	switch(tipo)
	{
		//Nível 0:
				case NAVE_TROPA_0:
					COR = c_white;
					NIVEL = 0;
					
					ALCANCE_REALOCAMENTO_px	= ALCANCE_R_px_PADRAO_NIVEL_0;
					ALCANCE_REALOCAMENTO_an	= ALCANCE_R_an_PADRAO_NIVEL_0;
					VELOCIDADE_REPOSICAO	= VELOCIDADE_R_PADRAO_NIVEL_0;
					
					N_FILHOS				= N_NAVES_PADRAO_NIVEL_0;
					VIDA_FILHOS				= VIDA_PADRAO_NIVEL_0;
					DANO_FILHOS				= DANO_PADRAO_NIVEL_0;
					RECARGA_ATAQUE_FILHOS	= RECARGA_ATAQUE_PADRAO_NIVEL_0;
					
					VANTAGEM_ELEMENTAR		= VANTAGEM_ELEMENTAR_PADRAO;
					DESVANTAGEM_ELEMENTAR	= DESVANTAGEM_ELEMENTAR_PADRAO;
					
					ELEMENTO = ELEMENTO_NEUTRO;
					break;

		//Nível 1:
				case NAVE_TROPA_1_TERRA:
					COR = c_TERRA;
					NIVEL = 1;
					
					ALCANCE_REALOCAMENTO_px	= ALCANCE_R_px_PADRAO_NIVEL_1*ALCANCE_R_px_BONUS_TERRA;
					ALCANCE_REALOCAMENTO_an	= ALCANCE_R_an_PADRAO_NIVEL_1*ALCANCE_R_an_BONUS_TERRA;
					VELOCIDADE_REPOSICAO	= VELOCIDADE_R_PADRAO_NIVEL_1;
					
					N_FILHOS				= N_NAVES_PADRAO_NIVEL_1;
					VIDA_FILHOS				= VIDA_PADRAO_NIVEL_1*VIDA_BONUS_TERRA;
					DANO_FILHOS				= DANO_PADRAO_NIVEL_1;
					RECARGA_ATAQUE_FILHOS	= RECARGA_ATAQUE_PADRAO_NIVEL_1;
					
					VANTAGEM_ELEMENTAR		= VANTAGEM_ELEMENTAR_PADRAO;
					DESVANTAGEM_ELEMENTAR	= DESVANTAGEM_ELEMENTAR_PADRAO;
					
					ELEMENTO = ELEMENTO_TERRA;
					break;
			
			
				case NAVE_TROPA_1_AGUA:
					COR = c_AGUA;
					NIVEL = 1;
					
					ALCANCE_REALOCAMENTO_px	= ALCANCE_R_px_PADRAO_NIVEL_1;
					ALCANCE_REALOCAMENTO_an	= ALCANCE_R_an_PADRAO_NIVEL_1;
					VELOCIDADE_REPOSICAO	= VELOCIDADE_R_PADRAO_NIVEL_1;
					
					N_FILHOS				= N_NAVES_PADRAO_NIVEL_1;
					VIDA_FILHOS				= VIDA_PADRAO_NIVEL_1;
					DANO_FILHOS				= DANO_PADRAO_NIVEL_1;
					RECARGA_ATAQUE_FILHOS	= RECARGA_ATAQUE_PADRAO_NIVEL_1;
					
					VANTAGEM_ELEMENTAR		= VANTAGEM_ELEMENTAR_PADRAO;
					DESVANTAGEM_ELEMENTAR	= DESVANTAGEM_ELEMENTAR_PADRAO;
					
					ELEMENTO = ELEMENTO_AGUA;
					break;
			
			
				case NAVE_TROPA_1_AR:
					COR = c_AR;
					NIVEL = 1;
					
					ALCANCE_REALOCAMENTO_px	= ALCANCE_R_px_PADRAO_NIVEL_1;
					ALCANCE_REALOCAMENTO_an	= ALCANCE_R_an_PADRAO_NIVEL_1;
					VELOCIDADE_REPOSICAO	= VELOCIDADE_R_PADRAO_NIVEL_1;
					
					N_FILHOS				= N_NAVES_PADRAO_NIVEL_1;
					VIDA_FILHOS				= VIDA_PADRAO_NIVEL_1;
					DANO_FILHOS				= DANO_PADRAO_NIVEL_1;
					RECARGA_ATAQUE_FILHOS	= RECARGA_ATAQUE_PADRAO_NIVEL_1;
					
					VANTAGEM_ELEMENTAR		= VANTAGEM_ELEMENTAR_PADRAO;
					DESVANTAGEM_ELEMENTAR	= DESVANTAGEM_ELEMENTAR_PADRAO;
					
					ELEMENTO = ELEMENTO_AR;
					break;
			
			
				case NAVE_TROPA_1_FOGO:
					COR = c_FOGO;
					NIVEL = 1;
					
					ALCANCE_REALOCAMENTO_px	= ALCANCE_R_px_PADRAO_NIVEL_1;
					ALCANCE_REALOCAMENTO_an	= ALCANCE_R_an_PADRAO_NIVEL_1;
					VELOCIDADE_REPOSICAO	= VELOCIDADE_R_PADRAO_NIVEL_1;
					
					N_FILHOS				= N_NAVES_PADRAO_NIVEL_1;
					VIDA_FILHOS				= VIDA_PADRAO_NIVEL_1;
					DANO_FILHOS				= DANO_PADRAO_NIVEL_1;
					RECARGA_ATAQUE_FILHOS	= RECARGA_ATAQUE_PADRAO_NIVEL_1;
					
					VANTAGEM_ELEMENTAR		= VANTAGEM_ELEMENTAR_PADRAO;
					DESVANTAGEM_ELEMENTAR	= DESVANTAGEM_ELEMENTAR_PADRAO;
					
					ELEMENTO = ELEMENTO_FOGO;
					break;
			

		//Nível 2:
				case NAVE_TROPA_2_TERRA:
					COR = c_TERRA;
					NIVEL = 2;
					
					ALCANCE_REALOCAMENTO_px	= ALCANCE_R_px_PADRAO_NIVEL_2*ALCANCE_R_px_BONUS_TERRA;
					ALCANCE_REALOCAMENTO_an	= ALCANCE_R_an_PADRAO_NIVEL_2*ALCANCE_R_an_BONUS_TERRA;
					VELOCIDADE_REPOSICAO	= VELOCIDADE_R_PADRAO_NIVEL_2;
					
					N_FILHOS				= N_NAVES_PADRAO_NIVEL_2;
					VIDA_FILHOS				= VIDA_PADRAO_NIVEL_2*VIDA_BONUS_TERRA;
					DANO_FILHOS				= DANO_PADRAO_NIVEL_2;
					RECARGA_ATAQUE_FILHOS	= RECARGA_ATAQUE_PADRAO_NIVEL_2;
					
					VANTAGEM_ELEMENTAR		= VANTAGEM_ELEMENTAR_PADRAO;
					DESVANTAGEM_ELEMENTAR	= DESVANTAGEM_ELEMENTAR_PADRAO;
					
					ELEMENTO = ELEMENTO_TERRA;
					break;
			
			
				case NAVE_TROPA_2_AGUA:
					COR = c_AGUA;
					NIVEL = 2;
					
					ALCANCE_REALOCAMENTO_px	= ALCANCE_R_px_PADRAO_NIVEL_2;
					ALCANCE_REALOCAMENTO_an	= ALCANCE_R_an_PADRAO_NIVEL_2;
					VELOCIDADE_REPOSICAO	= VELOCIDADE_R_PADRAO_NIVEL_2;
					
					N_FILHOS				= N_NAVES_PADRAO_NIVEL_2;
					VIDA_FILHOS				= VIDA_PADRAO_NIVEL_2;
					DANO_FILHOS				= DANO_PADRAO_NIVEL_2;
					RECARGA_ATAQUE_FILHOS	= RECARGA_ATAQUE_PADRAO_NIVEL_2;
					
					VANTAGEM_ELEMENTAR		= VANTAGEM_ELEMENTAR_PADRAO;
					DESVANTAGEM_ELEMENTAR	= DESVANTAGEM_ELEMENTAR_PADRAO;
					
					ELEMENTO = ELEMENTO_AGUA;
					break;
			
			
				case NAVE_TROPA_2_AR:
					COR = c_AR;
					NIVEL = 2;
					
					ALCANCE_REALOCAMENTO_px	= ALCANCE_R_px_PADRAO_NIVEL_2;
					ALCANCE_REALOCAMENTO_an	= ALCANCE_R_an_PADRAO_NIVEL_2;
					VELOCIDADE_REPOSICAO	= VELOCIDADE_R_PADRAO_NIVEL_2;
					
					N_FILHOS				= N_NAVES_PADRAO_NIVEL_2;
					VIDA_FILHOS				= VIDA_PADRAO_NIVEL_2;
					DANO_FILHOS				= DANO_PADRAO_NIVEL_2;
					RECARGA_ATAQUE_FILHOS	= RECARGA_ATAQUE_PADRAO_NIVEL_2;
					
					VANTAGEM_ELEMENTAR		= VANTAGEM_ELEMENTAR_PADRAO;
					DESVANTAGEM_ELEMENTAR	= DESVANTAGEM_ELEMENTAR_PADRAO;
					
					ELEMENTO = ELEMENTO_AR;
					break;
			
			
				case NAVE_TROPA_2_FOGO:
					COR = c_FOGO;
					NIVEL = 2;
					
					ALCANCE_REALOCAMENTO_px	= ALCANCE_R_px_PADRAO_NIVEL_2;
					ALCANCE_REALOCAMENTO_an	= ALCANCE_R_an_PADRAO_NIVEL_2;
					VELOCIDADE_REPOSICAO	= VELOCIDADE_R_PADRAO_NIVEL_2;
					
					N_FILHOS				= N_NAVES_PADRAO_NIVEL_2;
					VIDA_FILHOS				= VIDA_PADRAO_NIVEL_2;
					DANO_FILHOS				= DANO_PADRAO_NIVEL_2;
					RECARGA_ATAQUE_FILHOS	= RECARGA_ATAQUE_PADRAO_NIVEL_2;
					
					VANTAGEM_ELEMENTAR		= VANTAGEM_ELEMENTAR_PADRAO;
					DESVANTAGEM_ELEMENTAR	= DESVANTAGEM_ELEMENTAR_PADRAO;
					
					ELEMENTO = ELEMENTO_FOGO;
					break;
			
			
	}
	

}


